import { readdirSync, readFileSync, statSync, writeFileSync } from 'fs'
import { join, relative } from 'path'

const PUBLIC_DIR = join(import.meta.dir!, 'public')

function walk(dir: string): string[] {
  const files: string[] = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      files.push(...walk(full))
    } else {
      files.push(full)
    }
  }
  return files
}

const allFiles = walk(PUBLIC_DIR)
const entries: string[] = []

for (const file of allFiles) {
  const rel = '/' + relative(PUBLIC_DIR, file)
  const content = readFileSync(file)
  const base64 = content.toString('base64')
  const ext = file.substring(file.lastIndexOf('.') + 1)
  entries.push(`  ${JSON.stringify(rel)}: { data: ${JSON.stringify(base64)}, ext: ${JSON.stringify(ext)} }`)
}

const code = `// Auto-generated by embed.ts
export const files: Record<string, { data: string; ext: string }> = {
${entries.join(',\n')}
}
`

writeFileSync(join(import.meta.dir!, 'files.embed.ts'), code)
console.log(`✅ Embedded ${allFiles.length} files into files.embed.ts`)
